###Login as manager
POST http://localhost:3001/api/sessions
Content-Type: application/json

{"username": "luca@spg.com", "password": "FgKECe4w"}


###GET NOTIFICATIONS
GET http://localhost:3001/api/notifications

### asdds
PUT http://localhost:3001/api/topup/3/10
Content-Type: application/json

###GET PAYMENT FROM BOOKINGS IN STATE ISSUED OR PUT THEM IN STATE PENDING CANCELATION
GET http://localhost:3001/api/confirmAllBookings

### PROCESS BOOKING PENDING CANCELATION TO CANCEL THEM OR TO GET PAYMENT
GET http://localhost:3001/api/confirmAllBookingsPendingCancelation
