###Login as manager
POST http://localhost:3001/api/sessions
Content-Type: application/json

{"username": "luca@spg.com", "password": "FgKECe4w"}


###GET NOTIFICATIONS
GET http://localhost:3001/api/notifications