###Login as manager
POST http://localhost:3001/api/sessions
Content-Type: application/json

{"username": "luca@spg.com", "password": "FgKECe4w"}


###GET NOTIFICATIONS
GET http://localhost:3001/api/notifications

### asdds
PUT http://localhost:3001/api/topup/3/10
Content-Type: application/json

###GET PAYMENT FROM BOOKINGS IN STATE ISSUED OR PUT THEM IN STATE PENDING CANCELATION
GET http://localhost:3001/api/confirmAllBookings

### PROCESS BOOKING PENDING CANCELATION TO CANCEL THEM OR TO GET PAYMENT
GET http://localhost:3001/api/confirmAllBookingsPendingCancelation


###Send tg notifications of products available for purchase
GET http://localhost:3001/api/SNForAvailableProducts


###postunretrieved food
POST http://localhost:3001/api/unretrievedfood
Content-Type: application/json

{"date": "2021-12-10"}

### get unretrieved food of a week by sending the date of saturday
GET http://localhost:3001/api/unretrievedFoodOfWeek
Content-Type: application/json

{"date": "2021-12-25"}

###get unretrieved food of a month by sending month and year
GET http://localhost:3001/api/unretrievedFoodOfMonth
Content-Type: application/json

{"monthNum": 12, "year": 2021}

###get unretrieved food by productId
GET http://localhost:3001/api/unretrievedFoodByProductId/1
Content-Type: application/json



###get unretrieved food by product type
GET http://localhost:3001/api/unretrievedFoodByProductType/1
Content-Type: application/json

